server:
  port: 8080

spring:
  application:
    name: wallet-demo
  # Jpa
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create # can't touch this
    properties:
      hibernate.jdbc.timezone: UTC
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_demo_db
    username: wallet_demo_user
    password: password
    driver-class-name: org.postgresql.Driver

axon:
  serializer:
    events: jackson
    messages: jackson
    general: jackson
  eventhandling:
    processors:
      fraud:
        source: eventBus
        mode: subscribing
      mail:
        mode: tracking
      query:
        mode: tracking

