server:
  port: 8080

spring:
  application:
    name: wallet-dome
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

axon:
  serializer:
    events: jackson
  eventhandling:
    processors:
      fraud:
        source: eventBus
        mode: subscribing
      mail:
        mode: tracking

