server:
  port: 8080

spring:
  application:
    name: wallet-demo
  # Jpa
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop # can't touch this
    properties:
      hibernate.jdbc.timezone: UTC
      hibernate.dialect: com.demo.wallet.config.AxonPostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    mapping-resources: "DomainEventEntry.hbm.xml"

  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_demo_db
    username: wallet_demo_user
    password: password
    driver-class-name: org.postgresql.Driver

axon:
  serializer:
    events: jackson
  eventhandling:
    processors:
      fraud:
        source: eventBus
        mode: subscribing
      mail:
        mode: tracking
      query:
        mode: tracking